name: pro_miniaudio_example
description: "Demonstrates how to use the pro_miniaudio plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.15
  pro_miniaudio:
    path: ../
  svg_image: ^0.0.5


dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  pro_lints: ^2.0.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: false
