name: pro_miniaudio
description: "A Flutter plugin for miniaudio."
version: 0.0.12

repository: https://github.com/pro100andrey/pro_miniaudio
issue_tracker: https://github.com/pro100andrey/pro_miniaudio/issues
homepage: https://github.com/pro100andrey/pro_miniaudio
documentation: https://github.com/pro100andrey/pro_miniaudio/blob/main/README.md

environment:
  sdk: ^3.8.1
  flutter: '>=3.32.8'

dependencies:
  equatable: ^2.0.7
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  meta: ^1.16.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  ffigen: ^19.1.0
  flutter_test:
    sdk: flutter
  pro_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - miniaudio
  - audio
  - playback
  - capture

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
